### PR TITLE
Import liblsl for Android

### PR DESCRIPTION
**Pull request by tstenner**
> Hopefully Android Studio will one day support building a purely native library without redundancy.
- some guy frustrated by each compile/test cycle taking 12 minutes

This PR mainly does four things:

- it depends on an [experimental branch](https://github.com/tstenner/liblsl/tree/miniboost) that includes Boost 1.68 (needed for the newest NDK) and improves compile times by 10-40%
- it imports the [android library](https://github.com/labstreaminglayer/liblsl-Java/commit/8370656f9d2c80b0cc773096e153e661bec7c7dd) I just committed in each submodule instead of building it separately for each submodule
- jna is downloaded on demand and inserted in the APK so there's less need for user intervention
- it updates some dependencies to make the points listed above possible

### CODE REVIEW

**Comment by mgrivich** [comment]
It appears that you do some heavy lifting in gradlew, which is Linux only. Presumably this will fail on windows (which relies on gradlew.bat). I'd rather keep things platform independent and less convenient than platform dependent and convenient for only a subset of our users. In theory, we could keep both gradlew's up to date, but that is more effort (and complexity) than I'd like to put into a project that is only for demonstration purposes.

**Comment by tstenner** [comment]
Gradlew and gradlew.bat do the same (find java and use that to call the grade wrapper jar) so it's platform independant

**Comment by tstenner** [comment]
I'm on mobile so I can't confirm it, but the only reason there are more changes in gradlew than in gradlew.bat is that there was an older gradlew.bat already present. Both are just for convenience to download and run grade in case it's not already installed

**Comment by mgrivich** [comment]
Well, it is failing on Windows. You can figure out the reason.

I'm getting (in logcat):

> 2018-12-06 14:22:49.008 25661-25679/edu.ucsd.sccn.sendstringmarkers E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
>     Process: edu.ucsd.sccn.sendstringmarkers, PID: 25661
>     java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)
>         at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1039)
>         at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:999)
>         at com.sun.jna.Native.<clinit>(Native.java:191)
>         at com.sun.jna.Native.loadLibrary(Native.java:625)
>         at edu.ucsd.sccn.LSL.<clinit>(LSL.java:1106)
>         at edu.ucsd.sccn.LSL.local_clock(LSL.java)
>         at edu.ucsd.sccn.sendstringmarkers.MainActivity$2.run(MainActivity.java:41)
>         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

**Comment by tstenner** [comment]
JNA and that Android SDK/NDK versions had an issue loading the native library. I committed a workaround to liblsl-Java until JNA 5.2.0 is out, so after pulling that commit it should work.

**Comment by mgrivich** [comment]
I wiped labstreaminglayer and cloned it again (updating liblsl-Android to this branch). It is still failing with

>  java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path

in logcat.

**Comment by tstenner** [comment]
Ok, that needed a `git submodule update --remote LSL/liblsl-Java`. I've pushed the updated reference to sccn/labstreaminglayer so it's checked out automatically.

**Comment by mgrivich** [comment]
Now the build is failing at link. You need to stop pushing commits without testing them. Buy or borrow a Windows computer. In addition, your commit to liblsl-Java broke the Android Studio project in master. Please undo those commits and move them to a branch other than master.

```
Executing tasks: [:SendStringMarkers:assembleDebug]

Looking for liblsl-Java in the default path.
Change this via 'gradle -Pliblsl_java_dir=path/here if this fails

> Configure project :liblsl-Java
WARNING: ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.
WARNING: ABIs [armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI' not targeted by this project.

> Task :SendStringMarkers:buildInfoDebugLoader
> Task :liblsl-Java:preBuild UP-TO-DATE
> Task :liblsl-Java:preDebugBuild UP-TO-DATE
> Task :liblsl-Java:compileDebugAidl NO-SOURCE
> Task :liblsl-Java:compileDebugRenderscript UP-TO-DATE
> Task :liblsl-Java:checkDebugManifest UP-TO-DATE
> Task :liblsl-Java:generateDebugBuildConfig UP-TO-DATE
> Task :liblsl-Java:generateDebugResValues UP-TO-DATE
> Task :liblsl-Java:generateDebugResources UP-TO-DATE
> Task :liblsl-Java:packageDebugResources UP-TO-DATE
> Task :liblsl-Java:processDebugManifest UP-TO-DATE
> Task :liblsl-Java:generateDebugRFile UP-TO-DATE
> Task :liblsl-Java:prepareLintJar UP-TO-DATE
> Task :liblsl-Java:generateDebugSources UP-TO-DATE
> Task :liblsl-Java:javaPreCompileDebug

> Task :liblsl-Java:compileDebugJavaWithJavac
Note: C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\src\edu\ucsd\sccn\LSL.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :liblsl-Java:processDebugJavaRes NO-SOURCE
> Task :liblsl-Java:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :SendStringMarkers:checkDebugClasspath UP-TO-DATE
> Task :SendStringMarkers:preBuild UP-TO-DATE
> Task :SendStringMarkers:preDebugBuild UP-TO-DATE
> Task :SendStringMarkers:compileDebugAidl NO-SOURCE
> Task :liblsl-Java:packageDebugRenderscript NO-SOURCE
> Task :SendStringMarkers:compileDebugRenderscript UP-TO-DATE
> Task :SendStringMarkers:checkDebugManifest UP-TO-DATE
> Task :SendStringMarkers:generateDebugBuildConfig UP-TO-DATE
> Task :SendStringMarkers:prepareLintJar UP-TO-DATE
> Task :SendStringMarkers:mainApkListPersistenceDebug UP-TO-DATE
> Task :SendStringMarkers:generateDebugResValues UP-TO-DATE
> Task :SendStringMarkers:generateDebugResources UP-TO-DATE
> Task :SendStringMarkers:mergeDebugResources UP-TO-DATE
> Task :SendStringMarkers:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :SendStringMarkers:processDebugManifest
> Task :SendStringMarkers:splitsDiscoveryTaskDebug UP-TO-DATE
> Task :SendStringMarkers:processDebugResources
> Task :SendStringMarkers:generateDebugSources
> Task :SendStringMarkers:javaPreCompileDebug
> Task :SendStringMarkers:compileDebugJavaWithJavac
> Task :liblsl-Java:mergeDebugShaders
> Task :liblsl-Java:compileDebugShaders
> Task :liblsl-Java:generateDebugAssets
> Task :liblsl-Java:packageDebugAssets
> Task :SendStringMarkers:mergeDebugShaders
> Task :SendStringMarkers:compileDebugShaders
> Task :SendStringMarkers:generateDebugAssets
> Task :SendStringMarkers:mergeDebugAssets
> Task :SendStringMarkers:packageInstantRunResourcesDebug
> Task :SendStringMarkers:validateSigningDebug
> Task :SendStringMarkers:processInstantRunDebugResourcesApk
> Task :SendStringMarkers:checkManifestChangesDebug
> Task :SendStringMarkers:transformClassesWithExtractJarsForDebug
> Task :SendStringMarkers:transformClassesWithInstantRunVerifierForDebug
> Task :SendStringMarkers:transformClassesWithDependencyCheckerForDebug UP-TO-DATE
> Task :liblsl-Java:generateJsonModelDebug UP-TO-DATE

> Task :liblsl-Java:externalNativeBuildDebug
Build lsl armeabi-v7a
[1/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/chrono/src/chrono.cpp.o
[2/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/thread/src/pthread/thread.cpp.o
[3/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/program_options/src/convert.cpp.o
[4/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/atomic/src/lockpool.cpp.o
[5/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_iarchive.cpp.o
[6/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_archive.cpp.o
[7/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/archive_exception.cpp.o
[8/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_oserializer.cpp.o
[9/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/system/src/error_code.cpp.o
[10/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_oarchive.cpp.o
[11/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/extended_type_info_typeid.cpp.o
[12/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_serializer_map.cpp.o
[13/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_iserializer.cpp.o
[14/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/thread/src/pthread/once.cpp.o
[15/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/extended_type_info.cpp.o
[16/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/void_cast.cpp.o
[17/42] Linking CXX static library lslboost\liblslboost.a
[18/42] Building CXX object CMakeFiles/lsl.dir/src/api_config.cpp.o
[19/42] Building CXX object CMakeFiles/lsl.dir/src/common.cpp.o
[20/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_freefuncs_c.cpp.o
[21/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_outlet_c.cpp.o
[22/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_inlet_c.cpp.o
[23/42] Building CXX object CMakeFiles/lsl.dir/src/stream_info_impl.cpp.o
[24/42] Building CXX object CMakeFiles/lsl.dir/src/info_receiver.cpp.o
[25/42] Building CXX object CMakeFiles/lsl.dir/src/inlet_connection.cpp.o
[26/42] Building CXX object CMakeFiles/lsl.dir/src/data_receiver.cpp.o
[27/42] Building CXX object CMakeFiles/lsl.dir/src/consumer_queue.cpp.o
[28/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_continuous_resolver_c.cpp.o
[29/42] Building CXX object CMakeFiles/lsl.dir/src/pugixml/pugixml.cpp.o
[30/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_streaminfo_c.cpp.o
[31/42] Building CXX object CMakeFiles/lsl.dir/src/resolver_impl.cpp.o
[32/42] Building CXX object CMakeFiles/lsl.dir/src/sample.cpp.o
[33/42] Building CXX object CMakeFiles/lsl.dir/src/send_buffer.cpp.o
[34/42] Building CXX object CMakeFiles/lsl.dir/src/socket_utils.cpp.o
[35/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_xml_element_c.cpp.o
[36/42] Building CXX object CMakeFiles/lsl.dir/src/resolve_attempt_udp.cpp.o
[37/42] Building CXX object CMakeFiles/lsl.dir/src/time_postprocessor.cpp.o
[38/42] Building CXX object CMakeFiles/lsl.dir/src/stream_outlet_impl.cpp.o
[39/42] Building CXX object CMakeFiles/lsl.dir/src/udp_server.cpp.o
[40/42] Building CXX object CMakeFiles/lsl.dir/src/time_receiver.cpp.o
[41/42] Building CXX object CMakeFiles/lsl.dir/src/tcp_server.cpp.o
[42/42] Linking CXX shared library C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\build\intermediates\cmake\debug\obj\armeabi-v7a\liblsl.so
FAILED: cmd.exe /C "cd . && C:\AndroidStudio\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi22 --gcc-toolchain=C:/AndroidStudio/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=C:/AndroidStudio/android-sdk/ndk-bundle/sysroot -fPIC -isystem C:/AndroidStudio/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot C:/AndroidStudio/android-sdk/ndk-bundle/platforms/android-22/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -LC:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,liblsl.so -o C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\build\intermediates\cmake\debug\obj\armeabi-v7a\liblsl.so CMakeFiles/lsl.dir/src/api_config.cpp.o CMakeFiles/lsl.dir/src/common.cpp.o CMakeFiles/lsl.dir/src/consumer_queue.cpp.o CMakeFiles/lsl.dir/src/data_receiver.cpp.o CMakeFiles/lsl.dir/src/info_receiver.cpp.o CMakeFiles/lsl.dir/src/inlet_connection.cpp.o CMakeFiles/lsl.dir/src/lsl_continuous_resolver_c.cpp.o CMakeFiles/lsl.dir/src/lsl_freefuncs_c.cpp.o CMakeFiles/lsl.dir/src/lsl_inlet_c.cpp.o CMakeFiles/lsl.dir/src/lsl_outlet_c.cpp.o CMakeFiles/lsl.dir/src/lsl_streaminfo_c.cpp.o CMakeFiles/lsl.dir/src/lsl_xml_element_c.cpp.o CMakeFiles/lsl.dir/src/pugixml/pugixml.cpp.o CMakeFiles/lsl.dir/src/resolver_impl.cpp.o CMakeFiles/lsl.dir/src/resolve_attempt_udp.cpp.o CMakeFiles/lsl.dir/src/sample.cpp.o CMakeFiles/lsl.dir/src/send_buffer.cpp.o CMakeFiles/lsl.dir/src/socket_utils.cpp.o CMakeFiles/lsl.dir/src/stream_info_impl.cpp.o CMakeFiles/lsl.dir/src/stream_outlet_impl.cpp.o CMakeFiles/lsl.dir/src/tcp_server.cpp.o CMakeFiles/lsl.dir/src/time_postprocessor.cpp.o CMakeFiles/lsl.dir/src/time_receiver.cpp.o CMakeFiles/lsl.dir/src/udp_server.cpp.o  lslboost/liblslboost.a -lrt -latomic -lm "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_static.a" "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++abi.a" "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libunwind.a" "-ldl" && cd ."
C:/AndroidStudio/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lrt
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

> Task :liblsl-Java:externalNativeBuildDebug FAILED
> Task :SendStringMarkers:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':liblsl-Java:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\AndroidStudio\android-sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\.externalNativeBuild\cmake\debug\armeabi-v7a --target lsl}
  [1/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/chrono/src/chrono.cpp.o
  [2/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/thread/src/pthread/thread.cpp.o
  [3/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/program_options/src/convert.cpp.o
  [4/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/atomic/src/lockpool.cpp.o
  [5/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_iarchive.cpp.o
  [6/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_archive.cpp.o
  [7/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/archive_exception.cpp.o
  [8/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_oserializer.cpp.o
  [9/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/system/src/error_code.cpp.o
  [10/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_oarchive.cpp.o
  [11/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/extended_type_info_typeid.cpp.o
  [12/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_serializer_map.cpp.o
  [13/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/basic_iserializer.cpp.o
  [14/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/thread/src/pthread/once.cpp.o
  [15/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/extended_type_info.cpp.o
  [16/42] Building CXX object lslboost/CMakeFiles/lslboost.dir/libs/serialization/src/void_cast.cpp.o
  [17/42] Linking CXX static library lslboost\liblslboost.a
  [18/42] Building CXX object CMakeFiles/lsl.dir/src/api_config.cpp.o
  [19/42] Building CXX object CMakeFiles/lsl.dir/src/common.cpp.o
  [20/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_freefuncs_c.cpp.o
  [21/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_outlet_c.cpp.o
  [22/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_inlet_c.cpp.o
  [23/42] Building CXX object CMakeFiles/lsl.dir/src/stream_info_impl.cpp.o
  [24/42] Building CXX object CMakeFiles/lsl.dir/src/info_receiver.cpp.o
  [25/42] Building CXX object CMakeFiles/lsl.dir/src/inlet_connection.cpp.o
  [26/42] Building CXX object CMakeFiles/lsl.dir/src/data_receiver.cpp.o
  [27/42] Building CXX object CMakeFiles/lsl.dir/src/consumer_queue.cpp.o
  [28/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_continuous_resolver_c.cpp.o
  [29/42] Building CXX object CMakeFiles/lsl.dir/src/pugixml/pugixml.cpp.o
  [30/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_streaminfo_c.cpp.o
  [31/42] Building CXX object CMakeFiles/lsl.dir/src/resolver_impl.cpp.o
  [32/42] Building CXX object CMakeFiles/lsl.dir/src/sample.cpp.o
  [33/42] Building CXX object CMakeFiles/lsl.dir/src/send_buffer.cpp.o
  [34/42] Building CXX object CMakeFiles/lsl.dir/src/socket_utils.cpp.o
  [35/42] Building CXX object CMakeFiles/lsl.dir/src/lsl_xml_element_c.cpp.o
  [36/42] Building CXX object CMakeFiles/lsl.dir/src/resolve_attempt_udp.cpp.o
  [37/42] Building CXX object CMakeFiles/lsl.dir/src/time_postprocessor.cpp.o
  [38/42] Building CXX object CMakeFiles/lsl.dir/src/stream_outlet_impl.cpp.o
  [39/42] Building CXX object CMakeFiles/lsl.dir/src/udp_server.cpp.o
  [40/42] Building CXX object CMakeFiles/lsl.dir/src/time_receiver.cpp.o
  [41/42] Building CXX object CMakeFiles/lsl.dir/src/tcp_server.cpp.o
  [42/42] Linking CXX shared library C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\build\intermediates\cmake\debug\obj\armeabi-v7a\liblsl.so
  FAILED: cmd.exe /C "cd . && C:\AndroidStudio\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi22 --gcc-toolchain=C:/AndroidStudio/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=C:/AndroidStudio/android-sdk/ndk-bundle/sysroot -fPIC -isystem C:/AndroidStudio/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot C:/AndroidStudio/android-sdk/ndk-bundle/platforms/android-22/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -LC:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,liblsl.so -o C:\nbs\external\labstreaminglayer\LSL\liblsl-Java\build\intermediates\cmake\debug\obj\armeabi-v7a\liblsl.so CMakeFiles/lsl.dir/src/api_config.cpp.o CMakeFiles/lsl.dir/src/common.cpp.o CMakeFiles/lsl.dir/src/consumer_queue.cpp.o CMakeFiles/lsl.dir/src/data_receiver.cpp.o CMakeFiles/lsl.dir/src/info_receiver.cpp.o CMakeFiles/lsl.dir/src/inlet_connection.cpp.o CMakeFiles/lsl.dir/src/lsl_continuous_resolver_c.cpp.o CMakeFiles/lsl.dir/src/lsl_freefuncs_c.cpp.o CMakeFiles/lsl.dir/src/lsl_inlet_c.cpp.o CMakeFiles/lsl.dir/src/lsl_outlet_c.cpp.o CMakeFiles/lsl.dir/src/lsl_streaminfo_c.cpp.o CMakeFiles/lsl.dir/src/lsl_xml_element_c.cpp.o CMakeFiles/lsl.dir/src/pugixml/pugixml.cpp.o CMakeFiles/lsl.dir/src/resolver_impl.cpp.o CMakeFiles/lsl.dir/src/resolve_attempt_udp.cpp.o CMakeFiles/lsl.dir/src/sample.cpp.o CMakeFiles/lsl.dir/src/send_buffer.cpp.o CMakeFiles/lsl.dir/src/socket_utils.cpp.o CMakeFiles/lsl.dir/src/stream_info_impl.cpp.o CMakeFiles/lsl.dir/src/stream_outlet_impl.cpp.o CMakeFiles/lsl.dir/src/tcp_server.cpp.o CMakeFiles/lsl.dir/src/time_postprocessor.cpp.o CMakeFiles/lsl.dir/src/time_receiver.cpp.o CMakeFiles/lsl.dir/src/udp_server.cpp.o  lslboost/liblslboost.a -lrt -latomic -lm "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_static.a" "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++abi.a" "C:/AndroidStudio/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libunwind.a" "-ldl" && cd ."
  C:/AndroidStudio/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lrt
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
43 actionable tasks: 22 executed, 21 up-to-date


```

**Comment by tstenner** [comment]
> Now the build is failing at link. You need to stop pushing commits without testing them. Buy or borrow a Windows computer. In addition, your commit to liblsl-Java broke the Android Studio project in master.

While I agree in general and that I didn't test the master branch, 1) the link failure wasn't me, 2) [the CI](https://ci.appveyor.com/project/tstenner/liblsl-Java/build/1.12.38) is happy with liblsl-Java and 3) Android Studio on Windows is happy with liblsl-Java (see screenshot).

android_studio-fs8

On the master branch, the build quits with `error: package com.sun.jna does not exist`, even after putting jna-4.2.2.jar in the liblsl-Java folder as said in the readme. If you could paste the error message for that, I'd be happy to move that commit to the bench.

**Comment by mgrivich** [comment]
Do this:

Completely wipe (or rename) the labstreaminglayer folder.

git clone --recursive https://github.com/sccn/labstreaminglayer.git

cd labstreaminglayer

checkout master

cd LSL

cd liblsl-Android

git fetch origin

git checkout -b android_single_lib origin/android_single_lib

Open the Android Studio project on Windows, wait for it to finish 
configuring, then click play.

This does not work. Either make it so it does, or tell me where my 
mistake is.

**Comment by tstenner** [comment]
With tiny changes:

> git clone https://github.com/sccn/labstreaminglayer.git
cd labstreaminglayer
git submodule update --init LSL\*
cd LSL\liblsl-Android
git checkout android_single_lib
gradlew assemble

I was able to reproduce the error (`error: cannot find -lrt`). librt had been added to the list of required libs on Unix (ergo also android) because it was needed for some Python environments and the commit had been recorded as the current commit in liblsl. I've updated that so it works now, but you could always do this manually in your local repository (either `git submodule update --remote LSL/liblsl` or `cd LSL/liblsl; git checkout master; git pull`).

**Comment by mgrivich** [comment]
Thank you. It works now. Next time, please do more testing before requesting a merge.

**Pull request merged**
